# Do not use flag -O3 for both the g++ and icc compilers
CC = mpicc
CFLAGS = -Wall -g -O3 -align -std=c++11 -fPIC -axCORE-AVX2 -fast
LDFLAGS = -mkl
SOURCES = $(wildcard *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = fit

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

-include $(OBJECTS:.o=.d)

.cpp.o:
	$(CC) $(CFLAGS) -c $<
	$(CC) -MM $(CFLAGS) $< > $*.d

clean:
	rm -fv $(OBJECTS) $(EXECUTABLE) *.d
