help_str = """Usage: python3 pyfit-ff.py --compute-gis --run-training

Options:
	--compute-gis     Compute structural parameters using poscar file data,

	--run-training    Train the neural network file on existing structure 
	                  parameter data. If --compute-gis is specified, the
	                  structure parameters generated by that process can
	                  be immediately used. Set config.py values appropriately.
	                  This is the only flag specified by default if no others
	                  are specified.

	--graph-error     Display a graph of the loss of the network as a function
	                  of the training iteration after training is complete.
	                  You must have matplotlib installed to use this option.

Configuration:
	The file Config.py contains the majority of the important configuration
	parameters for the program. See the comments in that file for more details.

Notes:
	1) If the progress bars look bad, consider widening your terminal window.
	2) Neighbor list and Structure Parameter generation take somewhere on the
	   order of n^2 time where n is the number of atoms. Expect it to take a 
	   while for large datasets. Typical times are around 30 seconds for a 
	   datset of about 2,000 structures with a total of 14,000 atoms.
"""